# Generated by Django 3.1.5 on 2021-01-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210119_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('s', 'Science'), ('f', 'Fantasy'), ('fi', 'Fiction'), ('r', 'Romantic')], help_text='Enter a book genre (e.g. science, fiction)', max_length=200),
        ),
    ]
